title: "LJ Friedman"
description: "Good to meet you!"

theme: jekyll-theme-slate

nav:
  - title: "About Me"
    url: /about-me/
  - title: "Design Posts"
    url: /design-posts/
  - title: "Data Sources and Project Ideas"
    url: /data-sources-project-ideas/
  - title: "Photography"
    url: /photography/
  - title: "Music"
    url: /music/
